language: go

sudo: false

go:
  - 1.x

notifications:
  email: false

before_script:
  - go get github.com/stretchr/testify
  - go get ./...

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - make test
