language: go

sudo: false

go:
  - 1.x

notifications:
  email: false

before_script:
#  - go get github.com/stretchr/testify
#  - go get ./...
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...

script:
  - make test
