language: go

sudo: false

go:
  - 1.x

notifications:
  email: false

before_script:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...
  - go get github.com/mattn/goveralls

script:
  - go test -v -cover -race -coverprofile=/home/ubuntu/coverage.out
  - $GOPATH/bin/goveralls -coverprofile=/home/ubuntu/coverage.out -service=circle-ci
